[package]
name = "numburs"
version = "0.1.0"
edition = "2021"

[dependencies]
assert_approx_eq = "1.1.0"
derive_more = "0.99.17"
num-traits = "0.2.19"
paste = "1.0.15"
serde = { version = "1.0.210", features = ["derive"] }
